api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    #my ajout
    collection:
        pagination:
            # To enable or disable pagination for all resource collections by default.
            enabled: false # pas de pagination par defaut pour tout les ressources
            items_per_page: 5 #  tout les ressources
            client_items_per_page: true # choix donner au  client pour le nombre items par pagination
            client_enabled: true # choix donner au  client s'il veut la pagination ou pas !!
            # The name of the query parameter to set the number of items per page.
            items_per_page_parameter_name: 'count'
